# Generated by Django 2.0.2 on 2018-05-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
