# Generated by Django 2.0.2 on 2018-06-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0003_remove_group_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('status', models.CharField(blank=True, choices=[('W', 'Waiting for payment'), ('P', 'Payment complete')], default='W', max_length=1)),
                ('due_date', models.DateField(blank=True, default='')),
                ('complete', models.DateField(blank=True, default='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.Student')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.Training')),
            ],
        ),
    ]
