# Generated by Django 2.0.2 on 2018-06-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0004_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
