# Generated by Django 2.0.2 on 2018-06-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0005_auto_20180606_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='training',
        ),
        migrations.AddField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Manage.Group'),
            preserve_default=False,
        ),
    ]
