# Generated by Django 2.0.2 on 2018-06-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0008_auto_20180606_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='complete',
        ),
    ]
