# Generated by Django 2.0.2 on 2018-06-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0010_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('1', 'Attended'), ('2', "Didn't attend")], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
